# Numeric levels: 1=DEBUG, 2=INFO, 3=WARNING, 4=ERROR, 5=FATAL
# For production keep this >2 to print only WARNING/ERROR/FATAL.
app.logging.root-level=3

# Supported destinations: console, file, database
app.logging.destinations=console,file
app.logging.file.path=logs/custom-logger/application.log
app.logging.db.table=application_logs
